# Base16 Black Metal (Gorgoroth) - Alacritty Colors (Placeholder)
# Scheme by metalelf0 (https://github.com/metalelf0)

[colors.primary]
background = "0x000000"
foreground = "0xc1c1c1"

[colors.normal]
black = "0x000000"
red = "0x5f8787"
green = "0x9b8d7f"
yellow = "0x8c7f70"
blue = "0x888888"
magenta = "0x999999"
cyan = "0xaaaaaa"
white = "0xc1c1c1"

[colors.bright]
black = "0x333333"
red = "0x5f8787"
green = "0x9b8d7f"
yellow = "0x8c7f70"
blue = "0x888888"
magenta = "0x999999"
cyan = "0xaaaaaa"
white = "0xc1c1c1"

[[colors.indexed_colors]]
index = 16
color = "0xaaaaaa"

[[colors.indexed_colors]]
index = 17
color = "0x444444"

[[colors.indexed_colors]]
index = 18
color = "0x121212"

[[colors.indexed_colors]]
index = 19
color = "0x222222"

[[colors.indexed_colors]]
index = 20
color = "0x999999"

[[colors.indexed_colors]]
index = 21
color = "0x999999"

# Add other Alacritty specific sections if you find them for this theme, e.g.:
# [colors.cursor]
# text = "0x000000"
# cursor = "0xc1c1c1"
# [colors.selection]
# text = "0x000000"
# background = "0xc1c1c1"
